name: Node.js CI Workflow

on:
  push:
    branches:
      - main
      - test
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install --prefix ./client

      # Step 4: Build the project
      - name: Build project
        run: echo "Build project here"

  # Job 2: Test Job
  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    #   # Step 1: Allow access to MongoDB Atlas
    #   - name: Get the public IP of this runner
    #     id: get_gh_runner_ip
    #     shell: bash
    #     run: |
    #       echo "ip_address=$(curl -s https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"

    #   - name: Setup MongoDB Atlas CLI
    #     uses: mongodb/atlas-github-action@v0.2.0
    #     with:
    #       publicApiKey: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
    #       privateApiKey: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
    #       projectId: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}

    #   - name: Add runner IP to MongoDB access list
    #     shell: bash
    #     run: |
    #       atlas accessLists create ${{ steps.get_gh_runner_ip.outputs.ip_address }} --type ipAddress --comment "Temporary access for GH Action"

      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install --prefix ./client

      # Step 4: Set up environment variables from GitHub Secrets
      # - name: Setup environment variables
      #   run: |
      #     echo "NODE_ENV=test" >> $GITHUB_ENV
      #     echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Setup environment variables
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
      
      # Step 5: Run tests
      - name: Run tests
        run: npm test -- --testPathIgnorePatterns="tests"

      # # Step 6: Clean up
      # - name: Remove runner IP from MongoDB access list (cleanup)
      #   if: always()
      #   shell: bash
      #   run: |
      #     atlas accessLists delete ${{ steps.get_gh_runner_ip.outputs.ip_address }} --type ipAddress
